### ISSUE TITLE
No badge icons on iOS

### ISSUE THREAD

**Issue by Siumba** [dmatik/homeassistant-config#3]
I’ve been using your config as a template but I can’t seem to figure out the following. I’ve installed al necessary resources and on desktop the badge icons are shown perfectly. However on iOS, the SVG icons are not being displayed. 
![234A2002-61F8-44AB-9853-020810FBE71B](https://user-images.githubusercontent.com/5932051/116005611-0fcd6400-a608-11eb-8fb6-1e0f0f795b7a.png)

**Comment by dmatik** [comment]
Hi,
Sorry, I just saw this now. 
I also had this issue at some point. This has to do something with the styles on the SVG field in the template. Some CSS properties are not supported. 
Make sure you have same styles there. Or let me see you template.

**Comment by Siumba** [comment]
I tried using other svg values but it's fixed with your updated badge_button_svg_template :).

**Comment by dmatik** [comment]
Glad it's resolved. 
I did a lot of alignment and cleaning during last fee days.
