### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by milandzuris** [dmatik/homeassistant-config#5]
Hi whats the code only for Boiler Card, i trying find in cfg but don't find.

**Comment by dmatik** [comment]
Hi,
I use Custom Button Card with all its template functionality.
You can check out the templates here:
https://github.com/dmatik/homeassistant-config/tree/master/homeassistant/config/lovelace_tiles/templates/cards/card_switcher

You will also need more entities to be defined.
Please let me know if you any more help.
